# Generated by Django 3.2.18 on 2023-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0002_auto_20230225_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='degree_requirements',
            field=models.ManyToManyField(default=None, help_text='\nThe requirements needed to satisfy this degree.\n', related_name='requirements', to='degree.DegreeRequirement'),
        ),
    ]
