# Generated by Django 3.2.18 on 2023-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0003_degree_degree_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='degree_requirements',
        ),
        migrations.RemoveField(
            model_name='degreerequirement',
            name='q',
        ),
        migrations.RemoveField(
            model_name='degreerequirement',
            name='topics',
        ),
        migrations.AddField(
            model_name='degreerequirement',
            name='topics_provider',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='satisfied_by',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Cus'), (3, 'Num Courses'), (4, 'And'), (5, 'Or')], help_text='\nThe way in which this requirement is satisfied.  This is a string, and can be one of the\nfollowing:\n<table width=100%><tr><td>"ALL"</td><td>"Must take all courses to satisfy requirements"</td></tr><tr><td>"CUS"</td><td>"Must take courses with total number of CUs to satisfy requirements"</td></tr><tr><td>"NUM_COURSES"</td><td>"Must take a certain number of courses to satisfy requirements"</td></tr><tr><td>"AND"</td><td>"Contains a list of sub-requirements. Must take all sub-requirements to satisfy requirements"</td></tr><tr><td>"OR"</td><td>"Contains a list of sub-requirements. Can take any sub-requirement to satisfy requirements"</td></tr></table>', null=True),
        ),
    ]
