# Generated by Django 3.2.18 on 2023-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0004_auto_20230226_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreerequirement',
            name='topics_provider',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
