# Generated by Django 3.2.18 on 2023-02-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_alter_ngssrestriction_inclusive'),
        ('degree', '0005_alter_degreerequirement_topics_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreerequirement',
            name='topics_provider',
        ),
        migrations.AddField(
            model_name='degreerequirement',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='\nCourse objects which have this requirement.\n', related_name='requirements', to='courses.Topic'),
        ),
    ]
