# Generated by Django 3.2.18 on 2023-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0006_auto_20230226_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreerequirement',
            name='num',
            field=models.IntegerField(help_text='\nThe number of CUs required to satisfy this requirement\n', null=True),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='satisfied_by',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Any'), (3, 'Cus'), (4, 'And'), (5, 'Or')], help_text='\nThe way in which this requirement is satisfied.  This is a string, and can be one of the\nfollowing:\n<table width=100%><tr><td>"ALL"</td><td>"Must take all courses to satisfy requirements"</td></tr><tr><td>"ANY"</td><td>"Can take any course to satisfy requirements."</td></tr><tr><td>"CUS"</td><td>"Must take courses with total number of CUs to satisfy requirements"</td></tr><tr><td>"AND"</td><td>"Contains a list of sub-requirements. Must take all sub-requirements to satisfy requirements"</td></tr><tr><td>"OR"</td><td>"Contains a list of sub-requirements. Can take any sub-requirement to satisfy requirements"</td></tr></table>', null=True),
        ),
    ]
