# Generated by Django 3.2.23 on 2024-02-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0007_auto_20240207_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='rules',
        ),
        migrations.AddField(
            model_name='degree',
            name='all_rules',
            field=models.ManyToManyField(blank=True, help_text='\nAll the rules that make up this degree, including nested rules.\n', related_name='degrees', to='degree.Rule'),
        ),
        migrations.AddField(
            model_name='degree',
            name='rule',
            field=models.ForeignKey(blank=True, default=None, help_text='\nThe root rule associated with this degree.\n', on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='degree.rule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(help_text="\nThis rule's parent Rule if it has one. Null if this is a root rule\n(i.e., this rule is some degree's `.rule` root rule)\n", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='degree.rule'),
        ),
    ]
