# Generated by Django 3.2.18 on 2023-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0007_auto_20230226_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreerequirement',
            name='subrequirements',
            field=models.ManyToManyField(blank=True, help_text='\nThe subrequirements of this requirement.  This is a list of DegreeRequirement objects.\n', related_name='_degree_degreerequirement_subrequirements_+', to='degree.DegreeRequirement'),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='satisfied_by',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Any'), (3, 'Cus'), (4, 'And'), (5, 'Or')], help_text='\nThe way in which this requirement is satisfied.  This is a string, and can be one of the\nfollowing:\n<table width=100%><tr><td>"ALL"</td><td>"Must take all courses to satisfy requirements. If this option is selected, the list of subrequirements will be empty."</td></tr><tr><td>"ANY"</td><td>"Can take any course to satisfy requirements. If this option is selected, the list of subrequirements will be empty."</td></tr><tr><td>"CUS"</td><td>"Must take courses with total number of CUs to satisfy requirements"</td></tr><tr><td>"AND"</td><td>"Contains a list of sub-requirements. Must take all sub-requirements to satisfy requirements. If this option is selected, the list of topics will be empty."</td></tr><tr><td>"OR"</td><td>"Contains a list of sub-requirements. Can take any sub-requirement to satisfy requirements. If this option is selected, the list of topics will be empty."</td></tr></table>', null=True),
        ),
    ]
